'use client';

import { useState } from 'react';
import { CheckCircle2, ChevronRight, ClipboardCheck, FileText, Filter, GraduationCap, MessageSquare, Plus, Send, Upload, X } from 'lucide-react';

const submissions = [
  { name: 'Rahul Mehta', roll: '10B-18', task: 'Computer Networks Assignment', time: 'Today, 2:14 PM', status: 'Pending review', file: 'rahul_network_report.pdf' },
  { name: 'Anika Rao', roll: '10B-04', task: 'Computer Networks Assignment', time: 'Today, 1:52 PM', status: 'Pending review', file: 'anika_topology.docx' },
  { name: 'Kiran Das', roll: '10B-11', task: 'Computer Networks Assignment', time: 'Yesterday, 6:44 PM', status: 'Late', file: 'kiran_report.pdf' },
];

export default function TeacherHomeworkPage() {
  const [tab, setTab] = useState<'overview' | 'create' | 'review'>('overview');
  const [review, setReview] = useState<typeof submissions[number] | null>(null);
  const [notice, setNotice] = useState('');
  const publish = () => { setNotice('Homework published to Class 10B.'); setTab('overview'); setTimeout(() => setNotice(''), 2500); };
  const saveReview = (message: string) => { setNotice(message); setReview(null); setTimeout(() => setNotice(''), 2500); };
  const tabs = [{ id: 'overview', label: 'Overview' }, { id: 'create', label: 'Create homework' }, { id: 'review', label: 'Review queue' }] as const;
  return <div className="max-w-6xl mx-auto space-y-7 pb-10 text-left">
    <section className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-indigo-600">Homework management</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">Manage meaningful work.</h1><p className="mt-2 text-sm text-slate-500">A focused workflow for real-world tasks, submissions, feedback, and grading.</p></div><button onClick={() => setTab('create')} className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-900 px-4 py-3 text-xs font-semibold text-white hover:bg-slate-800"><Plus className="h-4 w-4" />Create homework</button></section>
    <nav className="flex gap-1 rounded-xl border border-slate-200 bg-white p-1 shadow-sm">{tabs.map((item) => <button key={item.id} onClick={() => setTab(item.id)} className={`flex-1 rounded-lg px-3 py-2.5 text-xs font-semibold transition ${tab === item.id ? 'bg-indigo-600 text-white shadow-sm' : 'text-slate-500 hover:bg-slate-50'}`}>{item.label}</button>)}</nav>
    {tab === 'overview' && <><div className="grid gap-4 sm:grid-cols-4">{[['12', 'Active homework'], ['27', 'Submitted'], ['6', 'Need review'], ['84%', 'On-time rate']].map(([value, label]) => <div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-2xl font-semibold text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-500">{label}</p></div>)}</div><section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="font-semibold text-slate-900">Computer Networks Assignment</h2><p className="mt-1 text-xs text-slate-500">Class 10B · Due today at 6:00 PM · 20 marks</p></div><button onClick={() => setTab('review')} className="text-xs font-semibold text-indigo-600">Open review queue</button></div><div className="grid gap-px bg-slate-100 sm:grid-cols-3">{[['18 / 28', 'Submitted'], ['6', 'Awaiting review'], ['2', 'Late']].map(([value, label]) => <div key={label} className="bg-white p-5"><p className="text-xl font-semibold text-slate-800">{value}</p><p className="mt-1 text-xs text-slate-500">{label}</p></div>)}</div></section></>}
    {tab === 'create' && <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-6 flex items-center gap-3 border-b border-slate-100 pb-5"><div className="rounded-xl bg-indigo-50 p-2.5 text-indigo-600"><ClipboardCheck className="h-5 w-5" /></div><div><h2 className="font-semibold text-slate-900">Create homework</h2><p className="text-xs text-slate-500">This is a professional assignment workflow, not a Learning Quest.</p></div></div><div className="grid gap-5 md:grid-cols-2"><Field label="Homework title" placeholder="e.g. Computer Networks Assignment" /><Select label="Subject" values={['Computer Science', 'Physics', 'History']} /><Select label="Class" values={['Class 10', 'Class 11', 'Class 12']} /><Field label="Section" placeholder="e.g. B" /><Field label="Chapter" placeholder="e.g. Network Topologies" /><Field label="Estimated time" placeholder="e.g. 45 minutes" /><TextArea label="Detailed description" placeholder="Explain the task students need to complete..." /><TextArea label="Instructions" placeholder="Submission, formatting, and research requirements..." /><TextArea label="Learning objective" placeholder="What should students demonstrate?" /><TextArea label="Rubric" placeholder="Criteria and marks allocation..." /></div><div className="mt-5 grid gap-4 rounded-2xl bg-slate-50 p-4 md:grid-cols-3"><Field label="Submission deadline" type="datetime-local" /><Field label="Maximum marks" placeholder="20" type="number" /><Select label="Late submissions" values={['Allowed — 10% penalty', 'Allowed — no penalty', 'Not allowed']} /></div><div className="mt-5 grid gap-4 md:grid-cols-2"><div className="rounded-xl border border-dashed border-slate-300 p-4"><Upload className="h-4 w-4 text-indigo-600" /><p className="mt-2 text-xs font-semibold text-slate-700">Attach reference materials</p><p className="mt-1 text-[11px] text-slate-400">PDFs, notes, links, images, or videos</p><input type="file" multiple className="mt-3 text-[11px]" /></div><div className="rounded-xl border border-slate-200 p-4"><p className="text-xs font-semibold text-slate-700">Accepted student submissions</p><div className="mt-3 flex flex-wrap gap-2">{['PDF', 'DOCX', 'PPTX', 'Images', 'ZIP', 'Code files', 'GitHub link', 'Text answer'].map((type) => <label key={type} className="rounded-lg bg-slate-100 px-2 py-1 text-[10px] text-slate-600"><input type="checkbox" defaultChecked className="mr-1 accent-indigo-600" />{type}</label>)}</div></div></div><div className="mt-6 flex justify-end"><button onClick={publish} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 text-xs font-semibold text-white hover:bg-indigo-700"><Send className="h-3.5 w-3.5" />Publish homework</button></div></section>}
    {tab === 'review' && <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 p-5"><div><h2 className="font-semibold text-slate-900">Review queue</h2><p className="mt-1 text-xs text-slate-500">Computer Networks Assignment · 3 submissions need attention</p></div><button className="inline-flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs text-slate-600"><Filter className="h-3.5 w-3.5" />Filter</button></div><div className="divide-y divide-slate-100">{submissions.map((item) => <button key={item.roll} onClick={() => setReview(item)} className="flex w-full items-center gap-4 px-5 py-4 text-left hover:bg-slate-50"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-slate-100 text-xs font-bold text-slate-600">{item.name.split(' ').map(n => n[0]).join('')}</div><div className="flex-1"><p className="text-sm font-semibold text-slate-800">{item.name} <span className="ml-1 text-xs font-normal text-slate-400">{item.roll}</span></p><p className="mt-1 text-xs text-slate-500">{item.file} · {item.time}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${item.status === 'Late' ? 'bg-rose-50 text-rose-700' : 'bg-amber-50 text-amber-700'}`}>{item.status}</span><ChevronRight className="h-4 w-4 text-slate-300" /></button>)}</div></section>}
    {notice && <div className="fixed bottom-6 right-6 z-50 flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-3 text-sm text-white shadow-xl"><CheckCircle2 className="h-4 w-4 text-emerald-400" />{notice}</div>}
    {review && <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/40 p-3 sm:p-8"><div className="mx-auto my-5 max-w-4xl rounded-3xl bg-white shadow-2xl"><div className="flex justify-between border-b border-slate-100 p-6"><div><p className="text-xs font-semibold text-indigo-600">{review.task}</p><h2 className="mt-1 text-xl font-semibold text-slate-900">{review.name} <span className="font-normal text-slate-400">· {review.roll}</span></h2><p className="mt-1 text-xs text-slate-500">Submitted {review.time}</p></div><button onClick={() => setReview(null)} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X className="h-5 w-5" /></button></div><div className="grid gap-6 p-6 md:grid-cols-[1fr_280px]"><div><div className="flex min-h-72 items-center justify-center rounded-2xl border border-slate-200 bg-slate-50"><div className="text-center"><FileText className="mx-auto h-10 w-10 text-indigo-400" /><p className="mt-3 text-sm font-semibold text-slate-700">{review.file}</p><button className="mt-3 text-xs font-semibold text-indigo-600">Preview / download submission</button></div></div><div className="mt-5"><label className="text-xs font-semibold text-slate-700">Feedback</label><textarea className="mt-2 min-h-28 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-indigo-400" placeholder="Give specific, actionable feedback..." /></div></div><aside className="space-y-4"><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-semibold text-slate-700">Grading</p><div className="mt-3 flex gap-2"><input type="number" placeholder="18" className="w-1/2 rounded-lg border border-slate-200 p-2 text-sm" /><span className="pt-2 text-sm text-slate-400">/ 20</span></div><select className="mt-3 w-full rounded-lg border border-slate-200 p-2 text-sm"><option>A+</option><option>A</option><option>B</option><option>Completed</option></select></div><button onClick={() => saveReview('Homework graded and the student has been notified.')} className="flex w-full items-center justify-center gap-2 rounded-xl bg-indigo-600 py-3 text-xs font-semibold text-white"><GraduationCap className="h-4 w-4" />Grade & notify</button><button onClick={() => saveReview('Resubmission requested with your feedback.')} className="flex w-full items-center justify-center gap-2 rounded-xl border border-slate-200 py-3 text-xs font-semibold text-slate-700"><MessageSquare className="h-4 w-4" />Request resubmission</button></aside></div></div></div>}
  </div>;
}
function Field({ label, placeholder, type = 'text' }: { label: string; placeholder?: string; type?: string }) { return <label className="block text-xs font-semibold text-slate-700">{label}<input type={type} placeholder={placeholder} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-normal outline-none focus:border-indigo-400" /></label>; }
function TextArea({ label, placeholder }: { label: string; placeholder: string }) { return <label className="block text-xs font-semibold text-slate-700">{label}<textarea placeholder={placeholder} className="mt-2 min-h-24 w-full rounded-xl border border-slate-200 p-3 text-sm font-normal outline-none focus:border-indigo-400" /></label>; }
function Select({ label, values }: { label: string; values: string[] }) { return <label className="block text-xs font-semibold text-slate-700">{label}<select className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-normal outline-none focus:border-indigo-400">{values.map(value => <option key={value}>{value}</option>)}</select></label>; }
