'use client';

import { useMemo, useState } from 'react';
import { CalendarClock, CheckCircle2, ChevronRight, Clock3, FileText, Paperclip, Send, Upload, X } from 'lucide-react';

type HomeworkStatus = 'Pending' | 'Submitted' | 'Under Review' | 'Graded' | 'Needs Resubmission';

const homework = [
  { id: 1, title: 'Network topology field report', subject: 'Computer Science', teacher: 'Ms. Sharma', due: 'Today, 6:00 PM', minutes: 45, marks: 20, priority: 'High', status: 'Pending' as HomeworkStatus, description: 'Document the network topology you observe at home or in the school lab. Label every device and explain the role it plays.', instructions: 'Submit a PDF or DOCX. Include one labelled diagram and a 150–200 word explanation.', formats: 'PDF, DOCX, Images', attachments: ['Topology reference.pdf', 'Lab diagram.png'] },
  { id: 2, title: 'Newton’s laws problem set', subject: 'Physics', teacher: 'Mr. Iyer', due: 'Tomorrow, 9:00 AM', minutes: 35, marks: 15, priority: 'Medium', status: 'Submitted' as HomeworkStatus, description: 'Solve the assigned motion problems, showing every step.', instructions: 'Write clearly. Scan or photograph your working before upload.', formats: 'PDF, Images', attachments: ['Problem set.pdf'] },
  { id: 3, title: 'Renaissance source analysis', subject: 'History', teacher: 'Mrs. Kapoor', due: 'Fri, 2 Aug', minutes: 60, marks: 25, priority: 'Medium', status: 'Needs Resubmission' as HomeworkStatus, description: 'Revise your source comparison using the feedback from your teacher.', instructions: 'Resubmit the corrected essay with citations.', formats: 'PDF, DOCX', attachments: ['Feedback rubric.pdf'] },
];

const statusStyle: Record<HomeworkStatus, string> = {
  Pending: 'bg-slate-100 text-slate-600', Submitted: 'bg-blue-50 text-blue-700', 'Under Review': 'bg-amber-50 text-amber-700', Graded: 'bg-emerald-50 text-emerald-700', 'Needs Resubmission': 'bg-rose-50 text-rose-700',
};

export default function StudentHomeworkPage() {
  const [selected, setSelected] = useState<typeof homework[number] | null>(null);
  const [submitted, setSubmitted] = useState<number[]>([2]);
  const [notice, setNotice] = useState('');
  const pending = useMemo(() => homework.filter((item) => !submitted.includes(item.id) && item.status !== 'Needs Resubmission').length, [submitted]);
  const submit = () => {
    if (!selected) return;
    setSubmitted((items) => [...new Set([...items, selected.id])]);
    setNotice('Submission saved. Your teacher has been notified.');
    setTimeout(() => { setNotice(''); setSelected(null); }, 1300);
  };

  return <div className="max-w-6xl mx-auto space-y-7 pb-10 text-left">
    <section className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between">
      <div><p className="text-xs font-bold uppercase tracking-[.18em] text-indigo-600">Homework management</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">Your work, in one clear place.</h1><p className="mt-2 max-w-xl text-sm text-slate-500">Offline and digital tasks live here. Learning Quest levels are separate and never require file uploads.</p></div>
      <div className="rounded-2xl border border-slate-200 bg-white px-4 py-3 shadow-sm"><p className="text-[11px] font-semibold uppercase tracking-wider text-slate-400">Next deadline</p><p className="mt-1 flex items-center gap-2 text-sm font-semibold text-slate-800"><Clock3 className="h-4 w-4 text-rose-500" />2h 18m remaining</p></div>
    </section>
    <div className="grid gap-4 sm:grid-cols-3">
      {[[`${pending}`, 'To complete', 'text-slate-900'], ['1', 'Waiting for review', 'text-amber-600'], ['18 / 20', 'Latest result', 'text-emerald-600']].map(([value, label, colour]) => <div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className={`text-2xl font-semibold ${colour}`}>{value}</p><p className="mt-1 text-sm text-slate-500">{label}</p></div>)}
    </div>
    <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="font-semibold text-slate-900">Assigned homework</h2><p className="mt-0.5 text-xs text-slate-500">Sorted by due date</p></div><button className="text-xs font-semibold text-indigo-600">All subjects</button></div><div className="divide-y divide-slate-100">{homework.map((item) => { const done = submitted.includes(item.id); return <button key={item.id} onClick={() => setSelected(item)} className="group flex w-full items-center gap-4 px-5 py-4 text-left transition hover:bg-slate-50"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-indigo-50 text-indigo-600"><FileText className="h-5 w-5" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-slate-800">{item.title}</h3><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${done ? statusStyle.Submitted : statusStyle[item.status]}`}>{done ? 'Submitted' : item.status}</span></div><p className="mt-1 text-xs text-slate-500">{item.subject} · {item.teacher} · {item.marks} marks</p></div><div className="hidden text-right sm:block"><p className="text-xs font-semibold text-slate-700">{item.due}</p><p className={`mt-1 text-[11px] ${item.priority === 'High' ? 'text-rose-600' : 'text-slate-400'}`}>{item.priority} priority</p></div><ChevronRight className="h-4 w-4 text-slate-300 group-hover:text-indigo-500" /></button>})}</div></section>
    {notice && <div className="fixed bottom-6 right-6 z-50 flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-3 text-sm text-white shadow-xl"><CheckCircle2 className="h-4 w-4 text-emerald-400" />{notice}</div>}
    {selected && <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/35 p-3 sm:p-8"><div className="mx-auto my-4 max-w-3xl rounded-3xl bg-white shadow-2xl"><div className="flex items-start justify-between border-b border-slate-100 p-6"><div><span className="text-xs font-semibold text-indigo-600">{selected.subject}</span><h2 className="mt-1 text-2xl font-semibold text-slate-900">{selected.title}</h2><p className="mt-2 text-sm text-slate-500">Assigned by {selected.teacher} · {selected.marks} marks</p></div><button onClick={() => setSelected(null)} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X className="h-5 w-5" /></button></div><div className="grid gap-7 p-6 md:grid-cols-[1fr_260px]"><div className="space-y-6"><div><h3 className="text-sm font-semibold text-slate-900">Task details</h3><p className="mt-2 text-sm leading-6 text-slate-600">{selected.description}</p></div><div><h3 className="text-sm font-semibold text-slate-900">Instructions</h3><p className="mt-2 text-sm leading-6 text-slate-600">{selected.instructions}</p></div><div><h3 className="text-sm font-semibold text-slate-900">Reference materials</h3><div className="mt-2 space-y-2">{selected.attachments.map((name) => <button key={name} className="flex w-full items-center gap-2 rounded-lg border border-slate-200 p-2.5 text-left text-xs font-medium text-slate-600 hover:border-indigo-200"><Paperclip className="h-3.5 w-3.5 text-indigo-500" />{name}</button>)}</div></div></div><aside className="space-y-4"><div className="rounded-2xl bg-slate-50 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Due</p><p className="mt-1 flex items-center gap-2 text-sm font-semibold text-slate-700"><CalendarClock className="h-4 w-4 text-rose-500" />{selected.due}</p><p className="mt-3 text-xs text-slate-500">Est. {selected.minutes} minutes</p><p className="mt-1 text-xs text-slate-500">Allowed: {selected.formats}</p></div><div className="rounded-2xl border-2 border-dashed border-slate-200 p-4"><Upload className="h-5 w-5 text-indigo-500" /><p className="mt-2 text-xs font-semibold text-slate-700">Attach your work</p><p className="mt-1 text-[11px] text-slate-400">PDF, DOCX, images, or link</p><input className="mt-3 block w-full text-[11px] text-slate-500" type="file" /></div><input placeholder="GitHub or Google Drive link" className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-xs outline-none focus:border-indigo-400" /><textarea placeholder="Comment for your teacher (optional)" className="min-h-20 w-full rounded-xl border border-slate-200 p-3 text-xs outline-none focus:border-indigo-400" /><button onClick={submit} className="flex w-full items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 py-3 text-xs font-semibold text-white hover:bg-indigo-700"><Send className="h-3.5 w-3.5" />Submit homework</button></aside></div></div></div>}
  </div>;
}
